const MINUTE = 60 * 1000;
const HOUR = 60 * MINUTE;
const DIFF_MILISECONDS_ALLOWED_FROM_LAST_INTERACTION = 2 * HOUR;
const DIFF_MILISECONDS_ALLOWED_FROM_LAST_INTERACTION_WHEN_FINISHED_CONVERSATION =
  5 * MINUTE;

module.exports = {
  MINUTE,
  HOUR,
  DIFF_MILISECONDS_ALLOWED_FROM_LAST_INTERACTION,
  DIFF_MILISECONDS_ALLOWED_FROM_LAST_INTERACTION_WHEN_FINISHED_CONVERSATION,
};
